In [ ]:
import numpy as np

In [15]:
import numpy as np
import time

def function(num):
    return num**2

def loop_speedtest(n):
    start = time.time()
    result = list(range(n))
    for i in result:
        result[i] = function(result[i])
    end = time.time()
    return end - start

def numpy_speedtest(n):
    start = time.time()
    result = np.arange(n)
    result = function(result)
    end = time.time()
    return end - start

reps = 100000000
print(loop_speedtest(reps))
print(numpy_speedtest(reps))

12.363215446472168
0.21956968307495117


In [ ]:
# PROBLEM 1: PUT IT IN REVERSE TERRY!

"""
    Make a function that takes in a 1D array. Reshape the array 
    so that it becomes a square matrix. Finally reverse the
    multi-dimensional array and return it.
"""

def reverseArray(arr):
    """
    >>> np.random.seed(12345)
    >>> myArr = np.random.randint(0, 10, size=(9))
    >>> myArr
    array([2, 5, 1, 4, 9, 5, 2, 1, 6])
    >>> reverseArray(myArr)
    array([[6, 1, 2],
           [5, 9, 4],
           [1, 5, 2]])

    >>> badLength = np.random.random(6)
    >>> reverseArray(badLength)
    Array length or dimension is not supported. Please try again.

    >>> wrongDim = np.random.random(4)
    >>> reverseArray(np.reshape(wrongDim, (2, 2)))
    Array length or dimension is not supported. Please try again.'
    """
    ...
    return ...

In [59]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

def perfectSquare(num):
    if int(np.sqrt(num)) == np.sqrt(num):
        return(True)
    else:
        return(False)
def reverseArray(input):
    if perfectSquare(len(input)) == True:
        np.reshape(input, (int(np.sqrt(len(input))), int(np.sqrt(len(input)))))
        return(input)
    else:
        return("array not supported")

print(reverseArray(my_array))

[1 2 3 4 5 6 7 8 9]


In [ ]:
# PROBLEM 2: IT'S NICE TO BE DIFFERENT

"""
    Given an array, return its sorted version with only the unique 
    elements, along with the count for each value.

    P.S. There is an easy way and a hard way xp
"""

def uniqueCounts(myArr):
    """
    >>> arr = np.array([10, 2, 5, 10, 8, 2, 8, 9])
    >>> uniqueCounts(arr)
    (array([ 2, 5,  8,  9, 10]), array([2, 1, 2, 1, 2]))
    """
    ...
    return ...

In [ ]:
def conditionedArr(myArr):
    """
    >>> np.random.seed(12345)
    >>> newArr = np.random.randint(0, 50, size=(4, 3))
    >>> newArr
    array([[34, 37, 29],
           [ 1, 36, 41],
           [37, 34, 29],
           [ 1, 49, 14]])
    >>> conditionedArr(newArr)
    array([[34, 39, 29],
           [18, 39, 41],
           [37, 39, 29],
           [18, 49, 28]])
    """
    ...
    return ...
